input:
    run_list_file: run_list.txt
    alien_input_path: /alice/data/2022/LHC22m/523399/raw/1030
    local_input_path: /home/lmichele/GITHUB/MFT_Cluster_Studies/CTF3
    ctf_input_path: /home/lmichele/GITHUB/MFT_Cluster_Studies/CTF3/tf
    prod_type: data
output:
    local_output_file: output/MFTAssessmentData.root
    analysis_output: MyAnalysisResultsData.root
